CREATE DATABASE IF NOT EXISTS gatherupdb;
USE gatherupdb;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  uid CHAR(36) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  name VARCHAR(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS events (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  uuid CHAR(36) NOT NULL UNIQUE,
  host_uid CHAR(36) NOT NULL,
  game_name VARCHAR(255),
  date_iso DATETIME,
  location VARCHAR(255),
  is_online BOOLEAN DEFAULT FALSE,
  description TEXT,
  max_participants INT DEFAULT 20,
  status VARCHAR(50),
  results JSON,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS join_requests (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  uuid CHAR(36) NOT NULL UNIQUE,
  event_uuid CHAR(36) NOT NULL,
  user_uid CHAR(36) NOT NULL,
  message TEXT,
  status VARCHAR(50),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);